spring.application.name=auth-service
server.port=8080

# Base de datos H2 en disco
spring.datasource.url=jdbc:h2:file:./data/mi-bd
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mantiene tablas entre reinicios
spring.jpa.hibernate.ddl-auto=update

# Consola H2 accesible desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Sin conexion a Eureka (en caso de microservicios)
eureka.client.enabled=false
